### ISSUE TITLE
"task" is not using the actual Taskfile.yaml location

### ISSUE THREAD

**Issue by ShivKJ** [mvdan/sh#1140]
Hi,

I am using **Taskfile** to automate some frequently used commands.

Instead of duplicating the `Taskfile.yaml` (PFA the sample file), I created a symlink to it in a different directory. However, when I run `task`, it displays the path of the directory containing the symlink, not the actual `Taskfile.yaml`.

I faced a similar issue with `Makefile`, but I resolved it by defining a variable: `PROJECT_DIR := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))`, in the `Makefile` (and then referencing the variable wherever needed), which gave me the path to the directory where the original `Makefile` (not the symlink) is located.

I would like to achieve the same with Taskfile—i.e., get the path to the directory containing the actual `Taskfile.yaml`. Is there a built-in variable/reference in Taskfile that provides this (if not, can we create one)? This would be useful for commands like docker, which require the path to the Dockerfile, especially if it is not in the current directory.

```yaml
version: 3

tasks:
    default:
        cmds:
            - echo ROOT_DIR={{.ROOT_DIR}}
            - echo TASKFILE_DIR={{.TASKFILE_DIR}}
```

**Comment by ShivKJ** [comment]
Able to resolve this, we can define a variable in `Taskfile.yaml` and use it,

```yaml
version: 3


vars:
    TASKFILE_DIR_ACTUAL: $(dirname $(readlink -f {{.TASKFILE}}))


tasks:
    default:
        cmds:
            - echo ROOT_DIR={{.ROOT_DIR}}
            - echo TASKFILE_DIR={{.TASKFILE_DIR}}
            - echo TASKFILE_DIR_ACTUAL={{.TASKFILE_DIR_ACTUAL}}

```

**Comment by ShivKJ** [comment]
Better way,

```yaml
versions: 3

vars:
    TASKFILE_DIR_ACTUAL:
        sh: dirname $(readlink -f {{.TASKFILE}})

tasks:
    default:
        cmds:
            - echo ROOT_DIR={{.ROOT_DIR}}
            - echo TASKFILE_DIR={{.TASKFILE_DIR}}
            - echo TASKFILE_DIR_ACTUAL={{.TASKFILE_DIR_ACTUAL}}
```
