### ISSUE TITLE
Shfmt from local repo files with unexpected error

### ISSUE THREAD

**Issue by richtong** [mvdan/sh#683]
I used the documentation in #554 which says add these lines

```
- repo: local
  hooks:
    id: shfmt
    name: shfmt
    language: golang
    additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.2.2]
    entry: shfmt
    args: [ -w ]
    types: [shell]
```

But I'm getting a go error and I don't really get go I admit I'm on go 1.16 on a Mac and get this error. I don't really understand go super well, but I'm guessing I need to initial my repo as a go module somehow (inconvenient as I don't use go for most of my repos). Or am I missing something?

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/bin/go', 'get', './...')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    go: no module declaration in go.mod. To specify the module path:
    	go mod edit -module=example.com/mod
```
