### ISSUE TITLE
shfmt -sr adds trailing space around subshells where newlines suffice

### ISSUE THREAD

**Issue by curiositycasualty** [mvdan/sh#715]
I've got something like this:
```bash
set -m

function items() {
  echo -e 'bah\nbee\nboo\nbar'
}

function eats_items() {
  echo "om nom nom, tasty item: ${1}"
}

for item in $(items); do
  (
    eats_items "$item"
  ) &
done

wait
```

And with `-sr`, a trailing space gets added to the opening parenthesis of the subshell:
```diff
--- /tmp/item_eater.bash.orig
+++ /tmp/item_eater.bash
@@ -11,7 +11,7 @@
 }

 for item in $(items); do
-  (
+  (
     eats_items "$item"
   ) &
 done

```

That feels unexpected to me since the parens is already technically surrounded by both newlines and spaces on both sides-- which semantically makes the subshell stick out pretty thoroughly.
I'm open to being wrong of course.

**Comment by mvdan** [comment]
Thanks, that definitely sounds like a bug. We never want to be keeping trailing whitespace in lines.

**Comment by mvdan** [comment]
Hm, I can't reproduce:

```
$ go install mvdan.cc/sh/v3/cmd/shfmt@master
go: downloading mvdan.cc/sh/v3 v3.4.0-0.dev.0.20210626100804-05043bb506b2
mvdan.cc/sh/v3/fileutil
mvdan.cc/sh/v3/syntax
mvdan.cc/sh/v3/cmd/shfmt
$ shfmt -version
v3.4.0-0.dev.0.20210626100804-05043bb506b2
$ cat f.sh
set -m

function items() {
	echo -e 'bah\nbee\nboo\nbar'
}

function eats_items() {
	echo "om nom nom, tasty item: ${1}"
}

for item in $(items); do
	(
		eats_items "$item"
	) &
done

wait
$ grep '\s$' f.sh
$ shfmt -l -w -sr f.sh
$ grep '\s$' f.sh
```

**Comment by curiositycasualty** [comment]
Doesn't seem to repro for me now either :/ sorry for the time waste.

**Comment by wizard-28** [comment]
@mvdan, I face this issue.

I'm using `shfmt` (v3.4.1) using `pre-commit` hooks. Here's my config.

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: file-contents-sorter
        files: packagelist
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
        types: []
        args: ["-o", "all", "-e", "2148", "-e", "SC2033", "-e", "SC2032", "-e", "SC2034"]
        files: '^.*\.(pacscript)$'
      - id: shfmt
        args: ["-i", "2", "-bn", "-ci", "-sr", "-kp", "-s"]
        types: []
        files: '^.*\.(pacscript)$'
# vim:set ft=yaml ts=2 sw=2 et:
```

Firstly `trailing-whitespace` hook removes the trailing whitespace (I've run `shfmt -sr` before), then the `shfmt` hook adds it back again.

Here's the concerned code:

```bash
  # Install resources
  ( 
    cd Space_Cadet
    sudo install -m644 ./*.DAT ./*.DOC ./*.MID ./*.BMP ./*.INF ./*.WAV -t "${pkgdir}/usr/lib/${pkgname}"
  )
```
