### ISSUE TITLE
interp: different behavior of `pipefail` for multiline scripts

### ISSUE THREAD

**Issue by Hades32** [mvdan/sh#870]
I'm using Task and hit this issue and was directed here: https://github.com/go-task/task/issues/392#issuecomment-1141300882

I want my script to fail on pipe errors. `cmd1` works/fails as expected, but `cmd2` never fails:
```yaml
  cmd1:
    cmds: 
    - set -o pipefail ; aws something | jq .someField
    - echo success # this never happens if aws fails

  cmd2:
    cmds: 
    - |
      set -e
      set -o pipefail
      aws something | jq .someField
      echo success # happens despite error in the aws command
```

Why does `pipefail` not work in the second case?
